[WIP] Added error messages in frontend
assistify/outlook-plugin pull request #20
Opened 2019-08-19 11:51 UTC by ThomasRoehl

please check if something else has to be done

2019-08-20 07:08 UTC, vickyokrm reviewed
'Next' button on the login screen is missing.

2019-08-20 07:14 UTC, vickyokrm requested changes

2019-08-20 07:14 UTC, vickyokrm commented on src/settings/login.js
> +                    const error = {};
Also ES5 here.

2019-08-21 09:12 UTC, ThomasRoehl commented
The login button is hidden as long as no valid url is entered ... see regex validation.

2019-08-21 09:51 UTC, janrudolph commented
> * button is greyed out and only clickable if regex validation does match

this one

2019-08-21 10:10 UTC, ThomasRoehl commented
should look like this now:
![image](https://user-images.githubusercontent.com/11913979/63423468-ad709900-c40c-11e9-9a31-0a3dce6bf0e2.png)

2019-08-21 13:27 UTC, vickyokrm commented
`https://team.assistify-test.noncd.db.de/asdadaada/adaadadada`  is validated as correct url.

2019-08-21 13:29 UTC, vickyokrm commented
Authentication validation is shown as `error` instead of actual error message.

2019-08-22 12:16 UTC, vickyokrm commented
`https://asdaa/asd`  is validated as a right url.

2019-08-22 12:24 UTC, vickyokrm requested changes
Messages snack bar view is not visible in the outlook.

2019-08-23 07:20 UTC, ThomasRoehl commented
For me it is visible in the webapp and in the local app.
Might be a problem on ie11 but i can not test that

2019-08-23 07:43 UTC, ThomasRoehl commented
> `https://asdaa/asd` is validated as a right url.

This should be fixed now. please try again

2019-08-30 07:43 UTC, merged