Feature/10 log events
assistify/outlook-plugin pull request #29
Opened 2019-08-21 16:10 UTC by jschirrmacher

Events will be logged only if hosted somewhere different than GitHub pages on a server or docker container running Node.js.

The small Node.js based server only serves the plugin files, and injects different URLs to the `manifest.xml` and `message.js` files to enable logging to a loggia-Host.

All URLs are given as environment variables to the Node.js server:

    LOGGER_URL=https://internal.server.running.loggia
    INTERNAL_PLUGIN_URL=https://internal.server.running.index.js
    PUBLIC_PLUGIN_URL=https://assistify.github.io/outlook-plugin

Optionally, you can use `DEBUG=true` to log all request to the console

2019-08-23 07:14 UTC, ThomasRoehl requested changes
We need a section in the readme for that.
After that it looks ok to merge

2019-08-23 07:14 UTC, ThomasRoehl commented on index.js
> +  .replace(new RegExp(process.env.PUBLIC_PLUGIN_URL, 'g'), process.env.INTERNAL_PLUGIN_URL)
This is pretty dirty but seems to work.

2019-09-02 07:00 UTC, vickyokrm commented
@jschirrmacher Do we need this PR?

2019-09-02 07:01 UTC, jschirrmacher commented
Not anymore.

2019-09-02 07:01 UTC, closed without merging